### ISSUE TITLE
Process user stories for possible use in readme, find in Project-board Archive and the proposal version (one of the last tasks)

### ISSUE THREAD

**Issue by stevelab1** [stevelab1/weather-pickmeup#44]
Template for US: “As a [persona], I [want to], [so that].”

...

not sure about following:

As a user, I want to search for the weather of a location, so that the website returns weather information of the searched location along with a related gif to cheer the user up.

As a user, I want to search for the weather of a location, so that the website returns weather information of the searched location along with a related gif to cheer the user up.

**Comment by lorettarehm** [comment]
Fixed by https://github.com/stevelab1/weather-pickmeup/commit/d95380905313f0301c99a19177c563bf81aca7c4
